// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinecraftSkins.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MinecraftSkins.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260221123617_AddMoreSeeding")]
    partial class AddMoreSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MinecraftSkins.Domain.Models.ExchangeRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("ExchangeRates");
                });

            modelBuilder.Entity("MinecraftSkins.Domain.Models.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BtcUsdRate")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<Guid?>("BuyerId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PriceUsdFinal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("PurchasedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SkinId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SkinId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("MinecraftSkins.Domain.Models.Skin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BasePriceUsd")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Skins");

                    b.HasData(
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440000"),
                            BasePriceUsd = 10.0m,
                            CreatedAtUtc = new DateTime(2026, 2, 21, 12, 36, 17, 313, DateTimeKind.Utc).AddTicks(4913),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Steve Classic"
                        },
                        new
                        {
                            Id = new Guid("67f12345-a1b2-c3d4-e5f6-7890abcdef12"),
                            BasePriceUsd = 15.5m,
                            CreatedAtUtc = new DateTime(2026, 2, 21, 12, 36, 17, 313, DateTimeKind.Utc).AddTicks(4915),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Creeper Hoodie"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            BasePriceUsd = 15.5m,
                            CreatedAtUtc = new DateTime(2026, 2, 21, 12, 36, 17, 313, DateTimeKind.Utc).AddTicks(4917),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Redstone Automaton"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f678-90ab-cdef-1234567890ab"),
                            BasePriceUsd = 25.0m,
                            CreatedAtUtc = new DateTime(2026, 2, 21, 12, 36, 17, 313, DateTimeKind.Utc).AddTicks(4918),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Diamond Sword Replica"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-7890-abcd-ef12-34567890abcd"),
                            BasePriceUsd = 12.99m,
                            CreatedAtUtc = new DateTime(2026, 2, 21, 12, 36, 17, 313, DateTimeKind.Utc).AddTicks(4956),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Enderman Plush"
                        },
                        new
                        {
                            Id = new Guid("d4e5f678-90ab-cdef-1234-567890abcdef"),
                            BasePriceUsd = 29.5m,
                            CreatedAtUtc = new DateTime(2026, 2, 21, 12, 36, 17, 313, DateTimeKind.Utc).AddTicks(4957),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Ghast Mood Lamp"
                        },
                        new
                        {
                            Id = new Guid("e5f67890-abcd-ef12-3456-7890abcdef12"),
                            BasePriceUsd = 14.0m,
                            CreatedAtUtc = new DateTime(2026, 2, 21, 12, 36, 17, 313, DateTimeKind.Utc).AddTicks(4958),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Piggy Bank (Pig)"
                        },
                        new
                        {
                            Id = new Guid("f67890ab-cdef-1234-5678-90abcdef1234"),
                            BasePriceUsd = 18.75m,
                            CreatedAtUtc = new DateTime(2026, 2, 21, 12, 36, 17, 313, DateTimeKind.Utc).AddTicks(4959),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Iron Golem Action Figure"
                        },
                        new
                        {
                            Id = new Guid("7890abcd-ef12-3456-7890-abcdef123456"),
                            BasePriceUsd = 8.5m,
                            CreatedAtUtc = new DateTime(2026, 2, 21, 12, 36, 17, 313, DateTimeKind.Utc).AddTicks(4961),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Nether Portal Poster"
                        },
                        new
                        {
                            Id = new Guid("890abcde-f123-4567-890a-bcdef1234567"),
                            BasePriceUsd = 5.0m,
                            CreatedAtUtc = new DateTime(2026, 2, 21, 12, 36, 17, 313, DateTimeKind.Utc).AddTicks(4962),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Wolf Tamed Keychain"
                        },
                        new
                        {
                            Id = new Guid("90abcdef-1234-5678-90ab-cdef12345678"),
                            BasePriceUsd = 16.0m,
                            CreatedAtUtc = new DateTime(2026, 2, 21, 12, 36, 17, 313, DateTimeKind.Utc).AddTicks(4963),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Skeleton Archer Figurine"
                        },
                        new
                        {
                            Id = new Guid("01234567-89ab-cdef-0123-456789abcdef"),
                            BasePriceUsd = 22.0m,
                            CreatedAtUtc = new DateTime(2026, 2, 21, 12, 36, 17, 313, DateTimeKind.Utc).AddTicks(4964),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Potion Bottle (Night Vision)"
                        });
                });

            modelBuilder.Entity("MinecraftSkins.Domain.Models.Purchase", b =>
                {
                    b.HasOne("MinecraftSkins.Domain.Models.Skin", null)
                        .WithMany()
                        .HasForeignKey("SkinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
